name: ModDamage
main: com.KoryuObihiro.bukkit.ModDamage.ModDamage
version: 0.9.6 test build
authors: [KoryuObihiro]
description: |
    Completely customize damage in Bukkit with ModDamage!
commands:
  moddamage:
    aliases: [md]
    description:
softdepend: [Multiverse-Core, elRegions, WorldGuard, bPermissions, PermissionsBukkit, PermissionsEx, mcMMO]
