name: ModDamage
main: com.KoryuObihiro.bukkit.ModDamage.ModDamage
version: 1.0 test build
author: KoryuObihiro
authors: [Spudstabber, ricochet1k]
description: |
    Completely customize damage in Bukkit with ModDamage!
commands:
  moddamage:
    aliases: [md]
    description:
softdepend: [Multiverse-Core, elRegions, WorldGuard, bPermissions, PermissionsBukkit, PermissionsEx, mcMMO]
