name: ModDamage
main: com.KoryuObihiro.bukkit.ModDamage.ModDamage
version: 0.9.5
authors: [KoryuObihiro]
description: |
    Completely customize damage in Bukkit with ModDamage!
commands:
  moddamage: 
    aliases: [md]
    description: