name: ModDamage
main: com.KoryuObihiro.bukkit.ModDamage.ModDamage
version: 0.9.4
authors: [KoryuObihiro]
description: |
    Completely configure damage in your worlds with ModDamage
commands:
  moddamage:
    aliases: [md]
    description: 
    usage: |
           /<command> 