name: ModDamage
main: com.ModDamage.ModDamage
version: 0.9.7
authors: [KoryuObihiro, Spudstabber, ricochet1k]
description: |
    Completely customize damage in Bukkit with ModDamage!
commands:
  moddamage:
    aliases: [md]
    description:
softdepend: [Multiverse-Core, elRegions, WorldGuard, bPermissions, PermissionsBukkit, PermissionsEx, mcMMO]
